Add header and headline
shasherazi/portfolio pull request #1
Opened 2022-11-29 13:42 UTC by shasherazi

Added the following

- Header (navbar)
- Headline section (introduction)

2022-11-29 14:13 UTC, Tadesse-Alemayehu requested changes
### Hi @shasherazi 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![EquatorialVictoriousBlackpanther-size_restricted](https://user-images.githubusercontent.com/69077061/204090500-5512fd84-cfd9-4aee-9d5d-8ee90740a92d.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 14:13 UTC, Tadesse-Alemayehu commented on src/index.html
> +        </p>
- [ ] Dear @shasherazi, for semantic reason it will be better to use heading tags here (which are less that `h1`, hence your main heading is already `h1`), something like `h2` or less.

2022-11-29 14:13 UTC, Tadesse-Alemayehu commented on src/index.html
> +      </section>
- [ ] Dear @shasherazi, I see you use a `fa-brands` icon, but as you can see down its falling to be visible on the website. 
- [ ] Also, Your background is a bit off compared with the Figma design. for better design let's address this.
- [ ] Another thing is,  Please use the appropriate font as in the design. in this case `Poppins`
### Figma design
![figma-icon](https://user-images.githubusercontent.com/69077061/204550706-2e780edd-aa9b-49a1-8913-c461d066a998.PNG)

### Your design
![your-icons](https://user-images.githubusercontent.com/69077061/204550739-9479c07f-d084-4471-842f-897a98c20c78.PNG)

2022-11-29 14:13 UTC, Tadesse-Alemayehu commented on src/index.html
> +      </section>
- [ ] Dear @shasherazi, Please make sure to use the `ul` tag for containing all the icons, and `li` for each list item(social media).

2022-11-29 14:37 UTC, shasherazi commented on src/index.html
> +      </section>
Again, these icons appear on my machine and one other machine I just tested. I suspect this is an internet connectivity issue on your side that icons are not being fetched correctly.

Same with the Poppins font, I am using it correctly in the CSS file.

The background depends on the screen resolution and aspect ratio of the viewing device. All a developer can do is to set it `background-size: cover;`.

2022-11-29 14:50 UTC, Tadesse-Alemayehu commented on src/index.html
> +    </header>
This might happen for a lot of reasons @shasherazi, Please make sure to push all your changes, preview your site on a live preview page like https://htmlpreview.github.io/. and make sure all is working. Once its working you are sure ask for a second review.

2022-11-29 14:54 UTC, Tadesse-Alemayehu commented on src/index.html
> +    </header>
Also, I cannot see the hamburger Icons on your repository so technically it does not exist on GitHub side. There is only the background image. 
![figma-icon](https://user-images.githubusercontent.com/69077061/204562459-5478ef83-8d84-4b91-bafa-d6148d15efcc.PNG)

2022-11-29 15:01 UTC, shasherazi commented on src/index.html
> +    </header>
I checked the https://raw.githack.com/ website, and the icons and fonts are displaying correctly there. They are displaying correctly on codepen.io too. The htmlpreview site has some issues. You can see those issues in the devtools console

2022-11-29 15:08 UTC, Tadesse-Alemayehu commented
This might happen for a lot of reasons @shasherazi, Please make sure to push all your changes, and preview your site on a live preview page like https://raw.githack.com/ or https://htmlpreview.github.io/. and make sure all is working. Once you are sure it's working ask for a second review.

2022-11-29 16:15 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @shasherazi , 


![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 16:15 UTC, ridwanediallo commented on src/style.css
> +  background-image: url(./assets/images/background.png);
- [ ] As noticed by the previous reviewer the `background-image` of your `headline-section` is too big compared to the original design. Please make sure to fix that. And remember that your project should be as much as possible similar to the original design.

### your design 

![Screenshot from 2022-11-29 16-05-40](https://user-images.githubusercontent.com/89228743/204581033-5edff70e-16d2-4ab0-b093-184fed91ac83.png)

#### The original design

![Screenshot from 2022-11-29 16-08-02](https://user-images.githubusercontent.com/89228743/204581560-fa52fa07-349e-4d8f-8be3-c766490ebb5d.png)

2022-11-29 16:15 UTC, ridwanediallo commented on src/index.html
> +            <i class="fa-brands fa-medium"></i>
- [ ] Your `medium` icon is different 😄. Please make sure to use the same one used in the original design.

### Your icons
![Screenshot from 2022-11-29 16-11-44](https://user-images.githubusercontent.com/89228743/204582519-4f29b568-6daa-4a49-a375-f94a93e02e26.png)
### the Figma design icons
![Screenshot from 2022-11-29 16-12-08](https://user-images.githubusercontent.com/89228743/204582778-7ee02a9e-df15-49d2-8d38-7cc10bcf0a82.png)

2022-11-29 16:51 UTC, shasherazi commented on src/style.css
> +  background-image: url(./assets/images/background.png);
Hello @ridwanediallo, I am actually stuck at this part. Btw I'm repeating this week, and last time I was able to get away with this slightly varying background image. But now that two reviewers have pointed this out, I googled how to modify this but couldn't find a way.

Can you give hints on how I can go around making the background look similar to the Figma design? Right now, I am using the background that I downloaded from the Figma file, which is slightly bigger.

2022-11-29 17:10 UTC, Tadesse-Alemayehu commented on src/style.css
> +  background-image: url(./assets/images/background.png);
hey @shasherazi, Please try to use a responsive width to make sure the background is no more than what you intend it to be. something like `background-size: 30vw`  also, refer to [this tutorial](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) for how to manage a background size. If you still have some issues I can send you a short video on how.

2022-11-30 10:49 UTC, OyePriscilla approved these changes
## Hi @shasherazi  😃  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Descriptive pull request message and title :heavy_check_mark: 
Linter error checks validated :heavy_check_mark: 
Commit messages are meaningful. :heavy_check_mark: 
GitHub flow observed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 10:52 UTC, merged